import Header from "./component/Header";
import { ReduxProvider } from "./component/ReduxProvider";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Amazon clone",
  description: "Generated by Amazon clone industry",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>
          <div className="sticky top-0 z-50">
            <Header />
          </div>
          {children}
        </ReduxProvider>
      </body>
    </html>
  );
}
